"""Initial schema

Revision ID: 3250137362e7
Revises: 
Create Date: 2026-05-30 09:11:08.820665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3250137362e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('feishu_user_id', sa.String(length=100), nullable=False, comment='飞书用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('role', sa.Enum('admin', 'project_manager', 'member', 'observer', name='userrole'), nullable=False, comment='角色'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_feishu_user_id'), 'users', ['feishu_user_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('events',
    sa.Column('event_type', sa.Enum('status_change', 'assignee_change', 'progress_update', 'date_adjust', 'risk_event', 'association', 'system_event', name='eventtype'), nullable=False, comment='事件类型'),
    sa.Column('entity_type', sa.Enum('project', 'task', 'meeting', name='entitytype'), nullable=False, comment='实体类型'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='实体ID'),
    sa.Column('triggered_by', sa.Integer(), nullable=False, comment='触发用户ID'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False, comment='发生时间'),
    sa.Column('change_details', sa.JSON(), nullable=True, comment='变更详情'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_entity_type'), 'events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容描述'),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='projectstatus'), nullable=False, comment='当前状态'),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'urgent', name='projecturgency'), nullable=False, comment='紧急程度'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='负责部门'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='负责人ID'),
    sa.Column('completion', sa.Integer(), nullable=True, comment='完成度(0-100)'),
    sa.Column('estimated_end_date', sa.Date(), nullable=True, comment='预计完成时间'),
    sa.Column('actual_end_date', sa.Date(), nullable=True, comment='实际完成时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('completion >= 0 AND completion <= 100', name='check_project_completion'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('risks',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='风险标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='风险描述'),
    sa.Column('status', sa.Enum('open', 'monitoring', 'resolved', name='riskstatus'), nullable=False, comment='风险状态'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='负责人ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_index(op.f('ix_risks_project_id'), 'risks', ['project_id'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('parent_task_id', sa.Integer(), nullable=True, comment='父任务ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='任务名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='负责人ID'),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'blocked', name='taskstatus'), nullable=False, comment='当前状态'),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='taskpriority'), nullable=False, comment='优先级'),
    sa.Column('completion', sa.Integer(), nullable=True, comment='完成度(0-100)'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='截止日期'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='完成时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('completion >= 0 AND completion <= 100', name='check_task_completion'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_project_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_entity_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_feishu_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
